modLoader="javafml"
loaderVersion="4,"
license="MIT"

[[mixins]]
config = "industrialforegoingadditional.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
logoFile="industrial_logo.png"
displayName="Industrial Foregoing Additional"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."industrialforegoingadditional"]]
modId = "neoforge"
type = "required"
versionRange = "21,"
ordering = "NONE"
side = "BOTH"

[[dependencies."industrialforegoingadditional"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,1.22]"
ordering = "NONE"
side = "BOTH"

[[dependencies."industrialforegoingadditional"]]
modId = "titanium"
type = "required"
versionRange = "[3.2.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."industrialforegoingadditional"]]
modId = "industrialforegoing"
type = "required"
versionRange = "[1.21-3.6.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."industrialforegoingadditional"]]
modId = "jei"
type = "optional"
versionRange = "[19.11.0,)"
ordering = "NONE"
side = "CLIENT"
